-- SELF JOIN
SELECT DISTINCT c1.CART_ID
FROM CART_PRODUCTS c1
    JOIN CART_PRODUCTS c2
    ON c1.CART_ID = c2.CART_ID
where c1.NAME = "우유" and c2.NAME = "요거트"

-- WHERE IN
SELECT DISTINCT C1.CART_ID
FROM CART_PRODUCTS C1
WHERE C1.NAME = '우유' AND C1.CART_ID IN (SELECT DISTINCT C2.CART_ID
    FROM CART_PRODUCTS C2
    WHERE C2.NAME = '요거트')